local nemici ={

  nemico1={
    immagine ="Images/Enemies/FallenAngel1/Idle.png",
    vita = 50000,
    danno = 100,
    armatura = 10,
    velocita = math.random(1, 10),
    width=119,
    height=160,
  },
  nemico2={
    immagine ="Images/Enemies/FallenAngel2/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=119,
    height=160,
  },
  nemico3={
    immagine ="Images/Enemies/FallenAngel3/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=119,
    height=160,
  },
  nemico4={
    immagine ="Images/Enemies/IceGolem/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=119,
    height=160,
  },
  nemico5={
    immagine ="Images/Enemies/EarthGolem/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=119,
    height=160,
  },
  nemico6={
    immagine ="Images/Enemies/MagmaGolem/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=119,
    height=160,
  },
  nemico7={
    immagine ="Images/Enemies/StoneGolem/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=150,
    height=122,
  },
  nemico8={
    immagine ="Images/Enemies/MudGolem/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=150,
    height=122,
  },
  nemico9={
    immagine ="Images/Enemies/WoodGolem/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=150,
    height=122,
  },
  nemico10={
    immagine ="Images/Enemies/Goblin/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=119,
    height=160,
  },
  nemico11={
    immagine ="Images/Enemies/Ogre/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=119,
    height=160,
  },
  nemico12={
    immagine ="Images/Enemies/Orco/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=119,
    height=160,
  },
  nemico13={
    immagine ="Images/Enemies/ReaperMan1/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=119,
    height=160,
  },
  nemico14={
    immagine ="Images/Enemies/ReaperMan2/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=119,
    height=160,
  },
  nemico15={
    immagine ="Images/Enemies/ReaperMan3/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=119,
    height=160,
  },
  nemico16={
    immagine ="Images/Enemies/Satiro1/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=129,
    height=131,
  },
  nemico17={
    immagine ="Images/Enemies/Satiro2/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=129,
    height=131,
  },
  nemico18={
    immagine ="Images/Enemies/Satiro3/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=129,
    height=131,
  },
  nemico19={
    immagine ="Images/Enemies/Troll1/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=193,
    height=133,
  },
  nemico20={
    immagine ="Images/Enemies/Troll2/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=193,
    height=133,
  },
  nemico21={
    immagine ="Images/Enemies/Troll3/Idle.png",
    vita = 9,
    danno = 3,
    armatura = 0,
    velocita = 3,
    width=193,
    height=133,
  }
}
return nemici
